### ISSUE TITLE
Not iOS6 compatible

### ISSUE THREAD

**Issue by iWhacko** [MatthewYork/MYBlurIntroductionView#11] opened 2013-12-06 14:08 UTC
The description of this github mentions its iOS6 compatible for iPhone. However there are a few things not compatible:
- use of NSString boundingRectWithSize:options:attributes:context is iOS7, and not available in iOS6. iOS6 still uses NSString sizeWithFont:ContrainedToSize.
- xib's cannot be compiled because it needs a later version of the SDK.

I propose the xib's be used in a seperate IB based example. Since a lot of developers prefer building their interface completely in code anyway.

**Comment by MatthewYork** [comment] 2013-12-06 15:02
I have built in xCode 5 and deployed to iOS 6 and 7 without problems. Also, the boundingRect... method is only called in iOS 7. You get a warning about it, but the code never actually hits sizeWithFont unless running iOS 6.

Also, please explain what you mean by the xib's needing a later version of the SDK. Xibs being turned into views has never been a problem regardless of SDK. 

Exactly what problems are you having? Maybe I can help if I know what the problem is.

**Comment by iWhacko** [comment] 2013-12-06 15:08
The reason I run into this problem is that I'm running xCode 4.6.3 with iOS 6.1 sdk. Because I'm not able to update at the moment. XCode cannot open the xib files, that's what it says:
![screen shot 2013-12-06 at 4 09 08 pm](https://f.cloud.github.com/assets/352797/1693083/646eea4e-5e88-11e3-9303-5abfe468791e.png)

Also, the boundingRect code is in an if(statement) for iOS7 that is correct, but the compiler still tries to compile it. You should use precompiler statements for that I think.

**Comment by MatthewYork** [comment] 2013-12-06 19:51
Ah, I understand now. Here's my best guess at making it work:

1) Remove the if statement on boundingRect and only use size to fit
2) Create you own xib files and use those as you would the ones in my demos. Basically, just generate a xib for yourself instead of using mine (which will error out).

I understand now what you mean about not being iOS 6 compatible, but through Xcode 5 it is, so I will keep that in the Readme. Also, sorry to hear you can't update!

Good luck. I'm going to close this issue.

**Closed as completed by MatthewYork** 2013-12-06 19:51 UTC
